export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES'
export const GET_DETAIL = 'GET_DETAIL'
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT'
export const ORDER_COUNTRIES = 'ORDER_COUNTRIES'
export const ORDEN_POPULATION = 'ORDEN_POPULATION'
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY'
export const RESET_FILTERED_COUNTRIES = 'RESET_FILTERED_COUNTRIES'
export const SET_SELECTED_ACTIVITY = 'SET_SELECTED_ACTIVITY'
export const ORDER_POPULATION_ASC = 'ORDER_POPULATION_ASC'
export const ORDER_POPULATION_DESC = 'ORDER_POPULATION_DESC'



